repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: trailing-whitespace
      exclude: '^.*__snapshots__.*$'
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      exclude: '(^.*migrations.*$|apps\/pretty_bad_protocol\/.*)'
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
        'flake8-tidy-imports',
      ]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      args: [--line-length=100, --safe]
      language_version: python3
      exclude: '(^.*migrations.*$|apps\/pretty_bad_protocol\/.*)'

- repo: https://github.com/prettier/prettier
  rev: '1.18.2' # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      files: '^.*\.jsx?$'

- repo: local
  hooks:
  - id: eslint
    name: eslint
    files: '^.*\.jsx?$'
    language: system
    pass_filenames: true
    entry: ./node_modules/.bin/eslint --color
    exclude: '^.*__snapshots__.*$'
